name: build package
on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: WoltLab Suite Package Creation
        uses: KittMedia/action-wsc-package-create@v1.1.0
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.tar.gz
          path: ${{ github.event.repository.name }}.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.event.repository.name }}.tar.gz"
          allowUpdates: true
          removeArtifacts: true
          commit: true
