name: build package
on: 
   push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Modify package version
        uses: Mudlet/xmlstarlet-action@master
        id: xml_replace
        with:
          args: ed -L --update "/package/packageinformation/version" -v $GITHUB_REF_NAME "package.xml"
      - name: WoltLab Suite Package Creation
        uses: KittMedia/action-wsc-package-create@v1.1.0
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.tar.gz
          path: ${{ github.event.repository.name }}.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.event.repository.name }}.tar.gz"
